function deepFreeze<T extends object>(obj: T): T {
  Object.keys(obj).forEach((prop) => {
    const value = (obj as any)[prop];
    if (value && typeof value === 'object') {
      deepFreeze(value);
    }
  });
  return Object.freeze(obj);
}

export const GameConfig = deepFreeze({
  core: {
    deltaTimeCap: 0.1,
    aimTolerance: 0.15,
  },
  camera: {
    fov: 75,
    near: 0.1,
    far: 5000,
    position: { x: 0, y: 0.5, z: 0 },
    lookAt: { x: 0, y: 0.5, z: -1 },
    backgroundColor: 0x000000,
  },
  player: {
    baseForwardSpeed: 100,
    forwardSpeeds: {
      DOGFIGHT: 100,
      SURFACE: 200,
      TRENCH: 500,
    },
    turnSpeedYaw: Math.PI / 1.5,
    turnSpeedPitch: Math.PI / 1.5,
    maxBank: Math.PI / 4,
    meshColor: 0x00ff00,
    meshSize: 1,
    maxShields: 6,
  },
  starField: {
    numStars: 1500,
    fieldSize: 500,
    starColor: 0xffffff,
    starSize: 0.5,
  },
  input: {
    sensitivity: 5.0,
    touchRadius: 100,
    centeringSpeed: 2.0,
  },
  ui: {
    highScore: 10000,
    damageFlashDuration: 150,
  },
  stage: {
    dogfightKillsThreshold: 10,
    deathStarDistance: 1000,
    trenchTransitionDistance: 100,
    trenchWidth: 100,
    trenchHeight: 100,
    deathStarSize: 100,
    deathStarHullSegmentsX: 12,
    deathStarHullSegmentsY: 8,
    deathStarTrenchSegments: 16,
    deathStarDishSegments: 12,
    deathStarDishSize: 20,
    deathStarTrenchWidth: 4,
    deathStarColor: 0x00ff00,
    deathStarDishColor: 0xccffcc,
    steeringStrength: 0.5,
    trenchLength: 5000,
    catwalkStartZ: -500,
    catwalkEndZ: -4500,
    catwalkSpacing: 500,
    catwalkYOffset: 20,
    catwalkDepth: 20,
    catwalkCollisionThreshold: 15, // Tolerance for Z-axis hit detection
    catwalkHeightThreshold: 15,    // Tolerance for Y-axis hit detection
    exhaustPortZOffset: 400,
    trenchMaxPitch: Math.PI / 6, // 30 degrees
    trenchMaxYaw: Math.PI / 6,   // 30 degrees
    catwalkColor: 0xaaaaaa,
    trenchWallColor: 0x00ff00,
    trenchVerticalDetailSpacing: 200,
    trenchHorizontalDetailSpacing: 50,
    trenchVerticalDetailColor: 0x00ff00,
    trenchHorizontalDetailColor: 0x00ff00,
    exhaustPortColor: 0xffff00,

    // Surface Stage
    surfaceLength: 10000,
    surfaceWidth: 2000,
    surfaceGridSpacing: 100,
    surfaceColor: 0x0000ff,
    surfaceFloorY: -50,
    surfaceFloorBounce: 2,
    surfaceCollisionDamage: 1,
    towerHeight: 50,
    towerWidth: 30,
    towerColor: 0xcc0000, // Red towers? Or grey? Design doc says "Red: Enemy fire". Let's stick to standard grey or red for enemies. Towers are enemies.
    towerSpawnInterval: 1.5,
    towerSpawnDistance: 1000,
    towerCleanupDistance: 200,
    towerMarginX: 50,
    towerPoints: 200,
    surfaceDuration: 30.0,
    deathStarSpawnAngle: Math.PI / 4,
  },
  tieFighter: {
    speed: 50,
    oscillationFrequency: 1.0,
    oscillationAmplitude: 15,
    distance: 60,
    meshColor: 0xff0000,
    meshSize: 1,
    points: 100,
    explosionVelocity: 50,
    spawnInterval: 3.0,
    cleanupDistance: 600,
    smartAI: {
      speed: 180,
      oscillationFreq: 2.0,
      oscillationAmp: 10,
      spawnDistanceBehind: 100,
      spawnRandomZ: 50,
      spawnRandomX: 40,
      spawnRandomY: 30,
      arcAmplitude: 40,
      arcFrequency: 0.5,
      arcIntensity: 0.8,
      arcFalloff: 60,
      verticalSwayRatio: 0.5,
      shadowDistance: -50,
      shadowDuration: 3.0,
      brakingZone: 60,
      stageThreshold: 0.1,
      escapeAccelerationDuration: 6.0,
      escapeFadeDuration: 3.0,
      rotationSpeed: 10.0,
      escapeFarRandomX: 0.4,
      escapeFarRandomY: 0.4,
      escapeFarZ: -1.0,
      escapeQuickRandomX: 2.5,
      escapeQuickRandomY: 2.0,
      escapeQuickZ: -0.5,
    },
  },
  laser: {
    speed: 2000,
    cooldown: 0.15,
    targetDepth: 200,
    boltLength: 30,
    thickness: 10,
    color: 0x00ffff,
    alternateColor: 0x0000ff,
    offsets: [
      { x: -1.2, y: 0.8 },
      { x: 1.2, y: 0.8 },
      { x: -1.2, y: -0.8 },
      { x: 1.2, y: -0.8 },
    ],
  },
  fireball: {
    meshSize: 3.0,
    meshColor: 0xff4500, // OrangeRed
    relativeSpeed: 40,
    fireRate: 2.0, // Seconds between shots
    collisionRadiusWorld: 2.0,
    collisionRadiusNDC: 0.05,
    points: 100,
    damage: 1,
    expirationDistance: 500,
    sparkleCount: 8,
    sparkleSize: 4.0,
    explosionVelocity: 30,
    explosionDuration: 0.5, // Seconds before removing exploded fireball
    hitZThreshold: -0.8,
    hitDistanceThreshold: 2.0,
    hitNDCThreshold: 1.2,
  },
  torpedo: {
    speedMultiplier: 2.0,
    cooldown: 2.0,
    bonusPoints: 10000,
    range: 2000,
    sparkleCount: 8,
    sparkleSize: 4.0,
    explosionVelocity: 30,
    explosionDuration: 0.5,
  },
  turret: {
    meshSize: 5.0,
    meshColor: 0x888888,
    fireRate: 3.0,
    range: 1500,
    spacing: 500,
    points: 200,
  },
} as const);
