function deepFreeze<T extends object>(obj: T): T {
  Object.keys(obj).forEach((prop) => {
    const value = (obj as any)[prop];
    if (value && typeof value === 'object') {
      deepFreeze(value);
    }
  });
  return Object.freeze(obj);
}

const ALL_STAGES = ['DOGFIGHT', 'SURFACE', 'TRENCH', 'EXPLOSION'] as const;

export const GameConfig = deepFreeze({
  core: {
    deltaTimeCap: 0.1,
    aimTolerance: 0.15,
    stages: ALL_STAGES,
  },
  camera: {
    fov: 75,
    near: 0.1,
    far: 5000,
    position: { x: 0, y: 0.5, z: 0 },
    lookAt: { x: 0, y: 0.5, z: -1 },
    backgroundColor: 0x000000,
  },
  player: {
    baseForwardSpeed: 100,
    forwardSpeeds: {
      DOGFIGHT: 100,
      SURFACE: 200,
      TRENCH: 500,
    },
    turnSpeedYaw: Math.PI / 1.5,
    turnSpeedPitch: Math.PI / 1.5,
    maxBank: Math.PI / 4,
    meshColor: 0x00ff00,
    meshSize: 1,
    maxShields: 6,
  },
  starField: {
    numStars: 1500,
    fieldSize: 500,
    starColor: 0xffffff,
    starSize: 0.5,
  },
  input: {
    sensitivity: 5.0,
    touchRadius: 100,
    centeringSpeed: 2.0,
  },
  ui: {
    highScore: 10000,
    damageFlashDuration: 150,
  },
  stages: {
    dogfight: {
      killsThreshold: 10,
    },
    surface: {
      length: 10000,
      width: 2000,
      gridSpacing: 100,
      color: 0x00ff00,
      verticalLineHeight: 5,
      verticalLineNoise: 20,
      verticalLineDensity: 0.1,
      floorY: -50,
      floorBounce: 2,
      floorClampBuffer: 10,
      collisionDamage: 1,
      towerHeight: 150,
      towerWidth: 30,
      towerColor: 0xffff00,
      towerTopColor: 0xffffff,
      towerSpawnInterval: 1.5,
      towerSpawnDistance: 1000,
      towerCleanupDistance: 200,
      towerMarginX: 50,
      towerPoints: 200,
      duration: 30.0,
      maxPitch: Math.PI / 4,
      maxYaw: Math.PI / 4,
      maxHeight: 150,
      fireballSize: 40.0,
      fireballSpeed: 400.0,
      towerExplosionVelocity: 20.0,
      towerExplosionColor: 0xffa500,
      towerDebrisRotationSpeed: 2.0,
      turretSize: 15,
      turretDensity: 0.3,
    },
    trench: {
      transitionDistance: 100,
      width: 100,
      height: 100,
      steeringStrength: 0.5,
      length: 5000,
      catwalkStartZ: -500,
      catwalkEndZ: -4500,
      catwalkSpacing: 500,
      catwalkYOffset: 20,
      catwalkDepth: 20,
      catwalkCollisionThreshold: 15,
      catwalkHeightThreshold: 15,
      exhaustPortZOffset: 400,
      maxPitch: Math.PI / 6,
      maxYaw: Math.PI / 6,
      catwalkColor: 0xaaaaaa,
      wallColor: 0x00ff00,
      verticalDetailSpacing: 200,
      horizontalDetailSpacing: 50,
      verticalDetailColor: 0x00ff00,
      horizontalDetailColor: 0x00ff00,
      exhaustPortColor: 0xffff00,
      turretSize: 20.0,
      fireballSize: 20.0,
    },
    deathStar: {
      distance: 1000,
      size: 100,
      hullSegmentsX: 12,
      hullSegmentsY: 8,
      trenchSegments: 16,
      dishSegments: 12,
      dishSize: 20,
      trenchWidth: 4,
      color: 0x00ff00,
      dishColor: 0xccffcc,
      spawnAngle: Math.PI / 4,
    },
  },
  progression: {
    wave1: ['DOGFIGHT', 'TRENCH', 'EXPLOSION'],
    default: ALL_STAGES,
  },
  tieFighter: {
    speed: 50,
    oscillationFrequency: 1.0,
    oscillationAmplitude: 15,
    distance: 60,
    meshColor: 0xff0000,
    meshSize: 1,
    points: 100,
    explosionVelocity: 50,
    spawnInterval: 3.0,
    cleanupDistance: 600,
    smartAI: {
      speed: 180,
      oscillationFreq: 2.0,
      oscillationAmp: 10,
      spawnDistanceBehind: 100,
      spawnRandomZ: 50,
      spawnRandomX: 40,
      spawnRandomY: 30,
      arcAmplitude: 40,
      arcFrequency: 0.5,
      arcIntensity: 0.8,
      arcFalloff: 60,
      verticalSwayRatio: 0.5,
      shadowDistance: -50,
      shadowDuration: 3.0,
      brakingZone: 60,
      stageThreshold: 0.1,
      escapeAccelerationDuration: 6.0,
      escapeFadeDuration: 3.0,
      rotationSpeed: 10.0,
      escapeFarRandomX: 0.4,
      escapeFarRandomY: 0.4,
      escapeFarZ: -1.0,
      escapeQuickRandomX: 2.5,
      escapeQuickRandomY: 2.0,
      escapeQuickZ: -0.5,
    },
  },
  laser: {
    speed: 2000,
    cooldown: 0.15,
    maxRange: 800,
    targetDepth: 200,
    boltLength: 30,
    thickness: 10,
    color: 0x00ffff,
    alternateColor: 0x0000ff,
    offsets: [
      { x: -1.2, y: 0.8 },
      { x: 1.2, y: 0.8 },
      { x: -1.2, y: -0.8 },
      { x: 1.2, y: -0.8 },
    ],
  },
  fireball: {
    meshSize: 3.0,
    meshColor: 0xff4500, // OrangeRed
    relativeSpeed: 40,
    fireRate: 2.0, // Seconds between shots
    collisionRadiusWorld: 2.0,
    collisionRadiusNDC: 0.05,
    points: 100,
    damage: 1,
    expirationDistance: 2000,
    sparkleCount: 8,
    sparkleSize: 4.0,
    explosionVelocity: 30,
    explosionDuration: 0.5, // Seconds before removing exploded fireball
    hitZThreshold: -0.8,
    hitDistanceThreshold: 2.0,
    hitNDCThreshold: 1.2,
  },
  torpedo: {
    speedMultiplier: 2.0,
    cooldown: 2.0,
    bonusPoints: 10000,
    range: 2000,
    sparkleCount: 8,
    sparkleSize: 4.0,
    explosionVelocity: 30,
    explosionDuration: 0.5,
  },
  turret: {
    meshSize: 5.0,
    meshColor: 0xff0000,
    fireRate: 3.0,
    range: 1500,
    spacing: 400,
    points: 200,
  },
  explosionStage: {
    duration: 5.0,
    escapeSpeed: 1000,
    shatterDelay: 2.0,
  },
  deathStarExplosion: {
    fragmentVelocity: 100,
    fragmentRotationSpeed: 2.0,
    particleCount: 50,
  },
  getDifficultyMultiplier(wave: number): number {
    return Math.min(1.0 + (wave - 1) * 0.2, 2.8);
  },
  getScaledInterval(base: number, multiplier: number): number {
    return base / multiplier;
  },
  getScaledSpeed(base: number, multiplier: number): number {
    return base * multiplier;
  },
} as const);
